### ISSUE TITLE
Examine datasets

### ISSUE THREAD

**Issue by zhangjiangqige** [cs654-twibo/twibo#2]
Datasets found so far:

(maybe need to read the paper of each dataset to understand the data)

## social circles: twitter
81k users, 1.77m edges
http://snap.stanford.edu/data/ego-Twitter.html

## higgs twitter dataset
with retweets/reply/mention
456k nodes, 14.8m edges
563k activities
https://snap.stanford.edu/data/higgs-twitter.html

## Twitter 2010
tweets containing URLs
2.86m tweets
73.7k users
36.7m links
https://www.isi.edu/~lerman/downloads/twitter/twitter2010.html

## Objectives

We can focus on the first two datasets for now. Need to summarize what exactly is contained in the *downloadable* files:
- how user relationship (followee/follower) is expressed
- does it contain the content and timestamp of tweets of a user
- how many users are there
- how many relationship are there (the total number of followees or followers)
- if user activities are contained in the dataset, what's the average/medium/maximum number of query per minute? (moving average with step size of 15 seconds)
- are the content and timestamp of the tweets of users in the dataset
- do both users of a relationship in the dataset? (may be a user that's not in the dataset)
- average, medium and maximum number of followers and followees

**Comment by xingweitian** [comment]
Copy that

**Comment by xingweitian** [comment]
- how user relationship (followee/follower) is expressed
   directed graph

- does it contain the content and timestamp of tweets of a user
   no

- how many users are there
   973 main users(ego network), the total number of users appeared in this dataset is 81306

- how many relationship are there (the total number of followees or followers)
   2420766

- if user activities are contained in the dataset, what's the average/medium/maximum number of query per minute? (moving average with step size of 15 seconds)
   no user activities contained in this dataset

- are the content and timestamp of the tweets of users in the dataset
   no

- do both users of a relationship in the dataset? (may be a user that's not in the dataset)
   no

**Comment by xingweitian** [comment]
For the first database:

- average followees: 15.988996182348979
- average followers: 29.773888444745097

- median followees: 0
- median followers: 8

- maximum followees: 3373
- maximum followers: 8660

- minimum followees: 0
- minimum followers: 0

**Comment by zhangjiangqige** [comment]
~~Please refine the format and move the content to the wiki pages [social circles](https://github.com/cs654-twibo/twibo/wiki/Social-circles:-twitter) and [higgs](https://github.com/cs654-twibo/twibo/wiki/Higgs-twitter)~~

Let's use google doc
